/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.contacteditor;
import javax.swing.*;
import java.util.regex.*;


public class ContactEditorUI extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldFname = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldLname = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldTitle = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldNname = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDFormat = new javax.swing.JComboBox<>();
        emailDetailPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textFieldEmail = new java.awt.TextField();
        emailList = new java.awt.List();
        addBtn = new java.awt.Button();
        editBtn = new java.awt.Button();
        removeBtn = new java.awt.Button();
        asDefaultBtn = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        radioBtnHTML = new javax.swing.JRadioButton();
        radioBtnPlainT = new javax.swing.JRadioButton();
        radioBtnCus = new javax.swing.JRadioButton();
        cancelBtn = new javax.swing.JButton();
        OkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Name", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Title:");

        jLabel4.setText("Nickname:");

        jLabel5.setText("Display Format:");

        jComboBoxDFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "HTML", "Text" }));

        javax.swing.GroupLayout nameDetailsLayout = new javax.swing.GroupLayout(nameDetails);
        nameDetails.setLayout(nameDetailsLayout);
        nameDetailsLayout.setHorizontalGroup(
            nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameDetailsLayout.createSequentialGroup()
                        .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldNname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBoxDFormat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        nameDetailsLayout.setVerticalGroup(
            nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameDetailsLayout.createSequentialGroup()
                .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(textFieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(textFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(nameDetailsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(textFieldNname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nameDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        emailDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Email", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel6.setText("Email Address:");

        addBtn.setLabel("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setLabel("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        removeBtn.setLabel("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        asDefaultBtn.setLabel("As Default");
        asDefaultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asDefaultBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Mail Format:");

        buttonGroup1.add(radioBtnHTML);
        radioBtnHTML.setText("HTML");

        buttonGroup1.add(radioBtnPlainT);
        radioBtnPlainT.setText("Plain Text");

        buttonGroup1.add(radioBtnCus);
        radioBtnCus.setText("Custom");

        javax.swing.GroupLayout emailDetailPanelLayout = new javax.swing.GroupLayout(emailDetailPanel);
        emailDetailPanel.setLayout(emailDetailPanelLayout);
        emailDetailPanelLayout.setHorizontalGroup(
            emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emailDetailPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(radioBtnHTML)
                        .addGap(18, 18, 18)
                        .addComponent(radioBtnPlainT)
                        .addGap(18, 18, 18)
                        .addComponent(radioBtnCus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(emailDetailPanelLayout.createSequentialGroup()
                        .addGroup(emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(emailDetailPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(asDefaultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(emailDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        emailDetailPanelLayout.setVerticalGroup(
            emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailDetailPanelLayout.createSequentialGroup()
                .addGroup(emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emailDetailPanelLayout.createSequentialGroup()
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asDefaultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(emailDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnHTML)
                    .addComponent(radioBtnPlainT)
                    .addComponent(radioBtnCus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        OkBtn.setText("OK");
        OkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(OkBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String PATTERN ="^[a-zA-Z0-9]{0,30}[@][a-zA-z0-9]{0,10}[.][a-zA-Z]{2,3}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(textFieldEmail.getText());
        if(textFieldEmail.getText().isEmpty())
        {
         JOptionPane.showMessageDialog(this,"Please Enter Email!!","Error",JOptionPane.ERROR_MESSAGE);   
        }else if(!match.matches()){
            JOptionPane.showMessageDialog(this,"Enter Valid Email!!","Error",JOptionPane.ERROR_MESSAGE);
        } else
        {
           emailList.add(textFieldEmail.getText());
           textFieldEmail.setText("");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
   
        if(emailList.getSelectedIndex() < 0)
        {
            JOptionPane.showMessageDialog(this,"No Email Selected","Error",JOptionPane.ERROR_MESSAGE); 
        }else 
        {
            
            textFieldEmail.setText(emailList.getSelectedItem());
           emailList.remove(emailList.getSelectedIndex());
           
        }
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
      
        if(emailList.getSelectedIndex() < 0)
        {
            JOptionPane.showMessageDialog(this,"Select an Email","Error",JOptionPane.ERROR_MESSAGE); 
        }else 
        {
          emailList.remove(emailList.getSelectedIndex());
             JOptionPane.showMessageDialog(this,"Succesfully Removed","Info",JOptionPane.INFORMATION_MESSAGE);
          
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void asDefaultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asDefaultBtnActionPerformed
        if(emailList.getSelectedIndex() < 0)
        {
            JOptionPane.showMessageDialog(this,"No Email Selected","Error",JOptionPane.ERROR_MESSAGE); 
        }else
        {
            JOptionPane.showMessageDialog(this,"Email Is Set To Default","Info",JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_asDefaultBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void OkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBtnActionPerformed
     if(textFieldFname.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this,"Please Enter First Name","Error",JOptionPane.ERROR_MESSAGE);
     }else if (textFieldLname.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this,"Please Enter Last Name","Error",JOptionPane.ERROR_MESSAGE);    
     }else if (textFieldTitle.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this,"Please Enter Your Title","Error",JOptionPane.ERROR_MESSAGE);
     }else if(textFieldNname.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(this,"Please Enter Your Nickname","Error",JOptionPane.ERROR_MESSAGE);
     }else if (emailList.getItemCount() == 0)
     {   
         JOptionPane.showMessageDialog(this,"Enter Atleast One Email","Error",JOptionPane.ERROR_MESSAGE);
         
     }else 
     {
          JOptionPane.showMessageDialog(this,"Your Details Has Been Successfully Saved","Error",JOptionPane.INFORMATION_MESSAGE);
          textFieldFname.setText("");
          textFieldLname.setText("");
          textFieldTitle.setText("");
          textFieldNname.setText("");
          emailList.removeAll();
          jComboBoxDFormat.setSelectedIndex(0);
          buttonGroup1.clearSelection();
          
     }
     
    }//GEN-LAST:event_OkBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkBtn;
    private java.awt.Button addBtn;
    private java.awt.Button asDefaultBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private java.awt.Button editBtn;
    private javax.swing.JPanel emailDetailPanel;
    private java.awt.List emailList;
    private javax.swing.JComboBox<String> jComboBoxDFormat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel nameDetails;
    private javax.swing.JRadioButton radioBtnCus;
    private javax.swing.JRadioButton radioBtnHTML;
    private javax.swing.JRadioButton radioBtnPlainT;
    private java.awt.Button removeBtn;
    private java.awt.TextField textFieldEmail;
    private java.awt.TextField textFieldFname;
    private java.awt.TextField textFieldLname;
    private java.awt.TextField textFieldNname;
    private java.awt.TextField textFieldTitle;
    // End of variables declaration//GEN-END:variables

    private void setText(int selectedIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
